name: foocipe_cooking_app
description: "A cooking app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  flutter_slidable: ^3.1.1
  animations: ^2.0.11
  file_picker: ^8.1.2
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  flutter_dotenv: ^5.2.1
  # firebase_core: ^2.15.1
  # firebase_storage: ^11.2.6
  # image_picker: ^1.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logos/foocipe-1.png
    - assets/icons/google-logo.png
    - assets/icons/facebook-logo.png
    - assets/icons/github-logo.png
    - assets/icons/cake.png
    - assets/icons/carrot.png
    - assets/icons/cherry.png
    - assets/icons/chicken.png
    - assets/icons/egg.png
    - assets/icons/hamburger.png
    - assets/icons/pizza.png
    - assets/icons/spoon.png
    - assets/icons/watermelon.png
    - assets/icons/list-button.png
    - assets/images/welcome_background-1.jpg
    - assets/images/welcome_background-2.jpg
    - assets/images/welcome_background-3.jpg
    

  fonts:
    - family: SF-Pro
      fonts:
        - asset: 'fonts/SF-Pro-Display-Bold.otf'
          weight: 700
        - asset: 'fonts/SF-Pro-Display-Medium.otf'
          weight: 500
        - asset: 'fonts/SF-Pro-Display-Regular.otf'
          weight: 400
        - asset: 'fonts/SF-Pro-Display-SemiBold.otf'
          weight: 600
          
    - family: Dongle
      fonts:
        - asset: 'fonts/Dongle-Regular.ttf'
          weight: 500
        - asset: 'fonts/Dongle-Light.ttf'
          weight: 400
        - asset: 'fonts/Dongle-Bold.ttf'
          weight: 600

    - family: Quicksand
      fonts:
        - asset: 'fonts/Quicksand-Bold.ttf'
          weight: 700
        - asset: 'fonts/Quicksand-SemiBold.ttf'
          weight: 600
        - asset: 'fonts/Quicksand-Medium.ttf'
          weight: 500
        - asset: 'fonts/Quicksand-Regular.ttf'
          weight: 400
        - asset: 'fonts/Quicksand-Light.ttf'
          weight: 300
        
    