name: foocipe_cooking_app
description: "A cooking app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/foocipe-1.png
    - assets/icons/Google.png
    - assets/images/welcome_background-1.jpg
    - assets/images/welcome_background-2.jpg
    - assets/images/welcome_background-3.jpg

  fonts:
    - family: SF-Pro
      fonts:
        - asset: 'fonts/SF-Pro-Display-Bold.otf'
          weight: 700
        - asset: 'fonts/SF-Pro-Display-Medium.otf'
          weight: 500
        - asset: 'fonts/SF-Pro-Display-Regular.otf'
          weight: 400
        - asset: 'fonts/SF-Pro-Display-SemiBold.otf'
          weight: 600
